server:
  port: 7000
spring:
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 7001

keycloak:
  realm: test-realm
  auth-server-url: http://localhost:8080/auth
  credentials:
    secret: XXX
  ssl-required: external
  resource: test-client
  cors: true
  principal-attribute: preferred_username

test:
  security-constraints:
    - authRoles: ["user"]
      securityCollections:
        - patterns: ['/']